# Generated by Django 4.0.1 on 2022-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_created_date_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='last_modified',
            new_name='updated_at',
        ),
    ]
