# Generated by Django 4.0.1 on 2022-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_reportschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='email',
            field=models.EmailField(default='NULL', max_length=254),
            preserve_default=False,
        ),
    ]
