# Generated by Django 4.0.1 on 2022-02-28 15:17

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_reportschedule_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='last_run_at',
            field=models.DateTimeField(default=tasks.models.default_last_runtime),
        ),
    ]
